---


- name: .NET Core | Configure needed apt extra packages
  package:
    name: "{{ dotnetcore_apt_extra_packages }}"
    state: present
  until: apt_tools_installed is succeeded
  register: apt_tools_installed

- name: .NET Core | Configure repositories
  apt:
    deb: "{{ dotnetcore_repository_config_package }}"

- name: .NET Core | Install .net core package
  apt:
    name: "{{ ( dotnetcore_package + '=' + dotnetcore_package_version ) if dotnetcore_package_version is defined  and dotnetcore_package_version is not sameas None else dotnetcore_package }}"  # noqa 204
    state: present
    update_cache: true
  until: dotnetcore_package_installed is succeeded
  register: dotnetcore_package_installed
